SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('TBU_SaleInvoice', 'TBU_MultipleReceivingVouchers', 'TBU_AccountAging')
ORDER BY TABLE_NAME, ORDINAL_POSITION
